### PR TITLE
Cloud run - and other fixes

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Staged!

https://app-oig6wem42a-uc.a.run.app/37104

**Comment by mit-mit** [comment]
I love how the staging test link redirects to a page titled 'Not responding' :-)

**Comment by kevmoo** [comment]
> I love how the staging test link redirects to a page titled 'Not responding' :-)

Ha!

**Comment by kevmoo** [comment]
Now I have ZERO clue to to update the domain to point to this.

```
;; Truncated, retrying in TCP mode.
 DNS server handling your query: localhost
 DNS server's address:	127.0.0.1#53
 
 Non-authoritative answer:
 dartbug.com	rdata_257 = \# 15 00056973737565706B692E676F6F67
 dartbug.com	has AAAA address 2001:4860:4802:38::15
 dartbug.com	has AAAA address 2001:4860:4802:32::15
 dartbug.com	has AAAA address 2001:4860:4802:34::15
 dartbug.com	has AAAA address 2001:4860:4802:36::15
 dartbug.com	text = "v=spf1 include:_spf.google.com ?all"
 dartbug.com	mail exchanger = 30 alt2.aspmx.l.google.com.
 dartbug.com	mail exchanger = 40 alt3.aspmx.l.google.com.
 dartbug.com	mail exchanger = 50 alt4.aspmx.l.google.com.
 dartbug.com	mail exchanger = 10 aspmx.l.google.com.
 dartbug.com	mail exchanger = 20 alt1.aspmx.l.google.com.
 dartbug.com
 	origin = ns1.googledomains.com
 	mail addr = dns-admin.google.com
 	serial = 2684355217
 	refresh = 21600
 	retry = 3600
 	expire = 1209600
 	minimum = 300
 Name:	dartbug.com
 Address: 216.239.36.21
 Name:	dartbug.com
 Address: 216.239.38.21
 Name:	dartbug.com
 Address: 216.239.32.21
 Name:	dartbug.com
 Address: 216.239.34.21
 dartbug.com	nameserver = ns1.googledomains.com.
 dartbug.com	nameserver = ns2.googledomains.com.
 dartbug.com	nameserver = ns3.googledomains.com.
 dartbug.com	nameserver = ns4.googledomains.com.
 
 Authoritative answers can be found from:
 ```

**Pull request merged**
